In [3]:
# import libs
import numpy as np
import pandas as pd

In [4]:
# Задание на повторение материала
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел 
# от 12 до 24 невключительно
# немного некорректно сформулировано - при такой формулировке возникают сомнения о включении числа 12

a = np.arange(12, 24)
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
# Создать 5 двумерных массивов разной формы из массива a. 
# Не использовать в аргументах метода reshape число -1.

a1 = a.reshape(3, 4)
print(a1)
a2 = a.reshape(4, 3)
print(a2)
a3 = a.reshape(2, 6)
print(a3)
a4 = a.reshape(6, 2)
print(a4)
a5 = a.reshape(12, 1)
print(a5)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [9]:
# Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

b1 = a.reshape(3, -1)
print(b1)
b2 = a.reshape(4, -1)
print(b2)
b3 = a.reshape(2, -1)
print(b3)
b4 = a.reshape(-1, 2)
print(b4)
b5 = a.reshape(-1, 1)
print(b5)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [17]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# Нет

# Создать массив из 3 строк и 4 столбцов, 
# состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, 
# равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

c = np.random.randn(3, 4)
print(c)

d = c.reshape(-1)
print(d)


[[ 0.60548507 -0.33413724  0.53654359 -1.8015443 ]
 [-0.44229124 -2.31328751 -0.43963731  1.54703345]
 [-0.26414182  1.90146986  0.97614559 -1.93450025]]
[ 0.60548507 -0.33413724  0.53654359 -1.8015443  -0.44229124 -2.31328751
 -0.43963731  1.54703345 -0.26414182  1.90146986  0.97614559 -1.93450025]


In [19]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

a = np.arange(20, 0, -2)

print(a)


[20 18 16 14 12 10  8  6  4  2]


In [21]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: 
# целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

b = np.array([[20], [18], [16], [14], [12], [10], [8], [6], [4], [2]])
print(b)

print(a.shape) # (10,)
print(b.shape) # (10, 1)


[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]
(10,)
(10, 1)


In [26]:
# Вертикально соединить массивы a и b. 
# a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, 
# состоящего из единиц. 
# Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))

print(c)


[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
# состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
print(a)

A = a.reshape(4, 3)
print(A)

At = np.transpose(A)
print(At)

B = A.dot(At)
print(B) # В - квадратная матрица 4х4

d = np.linalg.det(B)
print(d) # d = 0.0 => обратная матрица не существует


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
0.0


In [37]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
import numpy.random as rand
np.random.seed(42)


In [46]:
# Создайте одномерный массив c, 
# составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
# Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 

c = np.linspace(0, 16, 16)
print(c)

C = c.reshape(4, 4)
print(C)

D = B + C * 10
print(D)

d = np.linalg.det(D)
print(d) # d = -5.2047149260309924e-24 => обратная матрица существует

r = np.linalg.matrix_rank(D)
print(r) # 2

D_inv = np.linalg.inv(D)
print(D_inv)

for i in range(4):
    for j in range(4):
        if D_inv[i, j] > 0:
            D_inv[i, j] = 1
        if D_inv[i, j] < 0:
            D_inv[i, j] = 0
print(D_inv)
    

[ 0.          1.06666667  2.13333333  3.2         4.26666667  5.33333333
  6.4         7.46666667  8.53333333  9.6        10.66666667 11.73333333
 12.8        13.86666667 14.93333333 16.        ]
[[ 0.          1.06666667  2.13333333  3.2       ]
 [ 4.26666667  5.33333333  6.4         7.46666667]
 [ 8.53333333  9.6        10.66666667 11.73333333]
 [12.8        13.86666667 14.93333333 16.        ]]
[[  5.          24.66666667  44.33333333  64.        ]
 [ 56.66666667 103.33333333 150.         196.66666667]
 [108.33333333 182.         255.66666667 329.33333333]
 [160.         260.66666667 361.33333333 462.        ]]
-5.2047149260309924e-24
2
[[-2.28548058e+13  4.14995158e+13 -1.44346142e+13 -4.21009581e+12]
 [ 3.36807664e+13 -6.85644174e+13  3.60865355e+13 -1.20288452e+12]
 [ 1.20288452e+12  1.26302874e+13 -2.88692284e+13  1.50360564e+13]
 [-1.20288452e+13  1.44346142e+13  7.21730710e+12 -9.62307613e+12]]
[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 1. 1. 0.]]


In [ ]:
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
# а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
# для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

E = np.where(D_inv, B, C)

print(ind1)